#!/bin/bash

# Axway Amplify Central Webhook Setup Script
# Creates Integration, Secret, Webhook, and ResourceHook resources

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

print_header() {
    echo -e "${BLUE}=== $1 ===${NC}"
}

print_success() {
    echo -e "${GREEN}✓ $1${NC}"
}

print_error() {
    echo -e "${RED}✗ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠ $1${NC}"
}

print_info() {
    echo -e "${BLUE}ℹ $1${NC}"
}

# Check prerequisites
check_prerequisites() {
    print_header "Checking Prerequisites"
    
    # Check if Axway CLI is installed
    if ! command -v axway &> /dev/null; then
        print_error "Axway CLI is not installed"
        print_info "Install with: npm install -g @axway/axway-central-cli"
        exit 1
    fi
    print_success "Axway CLI found"
    
    # Check if user is authenticated
    if ! axway auth list &> /dev/null; then
        print_error "Not authenticated with Axway Central"
        print_info "Run: axway auth login"
        exit 1
    fi
    print_success "Authenticated with Axway Central"
}

# Get configuration from user
get_configuration() {
    print_header "Configuration Setup"
    
    # Integration name
    read -p "Enter integration name [servicenow-webhook-integration]: " INTEGRATION_NAME
    INTEGRATION_NAME=${INTEGRATION_NAME:-servicenow-webhook-integration}
    
    # Webhook URL
    read -p "Enter your webhook URL (e.g., https://your-domain.com/webhooks/axway): " WEBHOOK_URL
    if [ -z "$WEBHOOK_URL" ]; then
        print_error "Webhook URL is required"
        exit 1
    fi
    
    # API Key for webhook authentication
    read -p "Enter API key for webhook authentication: " -s API_KEY
    echo ""
    if [ -z "$API_KEY" ]; then
        print_error "API key is required"
        exit 1
    fi
    
    # Environment
    echo "Available environments:"
    echo "1) Development (apicentral-dev.axway.com)"
    echo "2) Staging (apicentral-stage.axway.com)"
    echo "3) Production (apicentral.axway.com)"
    read -p "Select environment [3]: " ENV_CHOICE
    ENV_CHOICE=${ENV_CHOICE:-3}
    
    case $ENV_CHOICE in
        1) ENVIRONMENT="dev" ;;
        2) ENVIRONMENT="stage" ;;
        3) ENVIRONMENT="prod" ;;
        *) print_error "Invalid environment choice"; exit 1 ;;
    esac
    
    print_success "Configuration collected"
    echo "Integration: $INTEGRATION_NAME"
    echo "Webhook URL: $WEBHOOK_URL"
    echo "Environment: $ENVIRONMENT"
    echo ""
}

# Create YAML configuration file
create_yaml_config() {
    print_header "Creating YAML Configuration"
    
    YAML_FILE="axway-webhook-config.yaml"
    
    cat > "$YAML_FILE" << EOF
# Axway Amplify Central Webhook Integration Configuration
# Generated by setup-axway-webhook.sh

group: management
apiVersion: v1alpha1
kind: Integration
name: ${INTEGRATION_NAME}
title: ServiceNow Webhook Integration
spec: {}
---
group: management
apiVersion: v1alpha1
kind: Secret
name: ${INTEGRATION_NAME}-auth-secret
title: Webhook Authentication Secret
metadata:
  scope:
    kind: Integration
    name: ${INTEGRATION_NAME}
spec:
  data:
    apikey: "${API_KEY}"
---
group: management
apiVersion: v1alpha1
kind: Webhook
name: ${INTEGRATION_NAME}-webhook
title: ServiceNow Integration Webhook
metadata:
  scope:
    kind: Integration
    name: ${INTEGRATION_NAME}
spec:
  enabled: true
  url: "${WEBHOOK_URL}"
  auth:
    secret:
      name: ${INTEGRATION_NAME}-auth-secret
      key: apikey
  headers:
    Content-Type: application/json
    User-Agent: amplify-central
---
group: management
apiVersion: v1alpha1
kind: ResourceHook
name: ${INTEGRATION_NAME}
title: API Lifecycle Events Hook
metadata:
  scope:
    kind: Integration
    name: ${INTEGRATION_NAME}
spec:
  triggers:
    - group: catalog
      scope:
        kind: Application
        name: "*"
      kind: AssetRequest
      name: "*"
      type:
        - created
        - updated
        - deleted
  webhooks:
    - ${INTEGRATION_NAME}-webhook
EOF

    print_success "YAML configuration created: $YAML_FILE"
}

# Deploy configuration to Axway Central
deploy_configuration() {
    print_header "Deploying Configuration to Axway Central"
    
    print_info "Creating resources in Axway Central..."
    if axway central apply -f "$YAML_FILE"; then
        print_success "Resources created successfully"
    else
        print_error "Failed to create resources"
        return 1
    fi
}

# Verify deployment
verify_deployment() {
    print_header "Verifying Deployment"
    
    print_info "Checking integration..."
    if axway central get integ "$INTEGRATION_NAME" &> /dev/null; then
        print_success "Integration '$INTEGRATION_NAME' found"
    else
        print_error "Integration '$INTEGRATION_NAME' not found"
        return 1
    fi
    
    print_info "Checking webhook..."
    if axway central get webhook "${INTEGRATION_NAME}-webhook" -s "$INTEGRATION_NAME" &> /dev/null; then
        print_success "Webhook '${INTEGRATION_NAME}-webhook' found"
    else
        print_error "Webhook '${INTEGRATION_NAME}-webhook' not found"
        return 1
    fi
    
    print_info "Checking resource hooks..."
    if axway central get resourcehook "${INTEGRATION_NAME}-api-lifecycle-hook" -s "$INTEGRATION_NAME" &> /dev/null; then
        print_success "API lifecycle hook found"
    else
        print_error "API lifecycle hook not found"
        return 1
    fi
    
    if axway central get resourcehook "${INTEGRATION_NAME}-subscription-hook" -s "$INTEGRATION_NAME" &> /dev/null; then
        print_success "Subscription hook found"
    else
        print_error "Subscription hook not found"
        return 1
    fi
}

# Create service account for API callbacks
create_service_account() {
    print_header "Creating Service Account for API Callbacks"
    
    print_info "This service account will be used for making API callbacks to Axway"
    
    read -p "Create service account? [y/N]: " CREATE_SA
    if [[ "$CREATE_SA" =~ ^[Yy]$ ]]; then
        SA_NAME="${INTEGRATION_NAME}-service-account"
        
        if axway central create serviceaccount "$SA_NAME" --output json > service-account.json; then
            print_success "Service account created: $SA_NAME"
            print_info "Service account details saved to: service-account.json"
            
            # Extract client ID and secret for environment setup
            if command -v jq &> /dev/null; then
                CLIENT_ID=$(jq -r '.clientId' service-account.json 2>/dev/null)
                CLIENT_SECRET=$(jq -r '.clientSecret' service-account.json 2>/dev/null)
                
                if [ "$CLIENT_ID" != "null" ] && [ "$CLIENT_SECRET" != "null" ]; then
                    print_success "Service account credentials extracted"
                    SA_CREATED=true
                else
                    print_warning "Could not extract credentials from JSON response"
                fi
            else
                print_warning "jq not found - please extract credentials manually from service-account.json"
            fi
        else
            print_error "Failed to create service account"
        fi
    else
        print_info "Skipping service account creation"
    fi
}

# Generate environment configuration
generate_env_config() {
    print_header "Environment Configuration"
    
    ENV_FILE="axway-webhook.env"
    
    cat > "$ENV_FILE" << EOF
# Axway Webhook Configuration
# Generated by setup-axway-webhook.sh

# Webhook Authentication (from the secret in your YAML config)
AXWAY_WEBHOOK_TOKEN="${API_KEY}"

# API Base URL (adjust based on your environment)
EOF

    case $ENVIRONMENT in
        "dev") echo "AXWAY_API_BASE_URL=https://apicentral-dev.axway.com" >> "$ENV_FILE" ;;
        "stage") echo "AXWAY_API_BASE_URL=https://apicentral-stage.axway.com" >> "$ENV_FILE" ;;
        "prod") echo "AXWAY_API_BASE_URL=https://apicentral.axway.com" >> "$ENV_FILE" ;;
    esac
    
    if [ "$SA_CREATED" = true ] && [ -n "$CLIENT_ID" ] && [ -n "$CLIENT_SECRET" ]; then
        cat >> "$ENV_FILE" << EOF

# Service Account for API Callbacks
AXWAY_SERVICE_ACCOUNT_CLIENT_ID="${CLIENT_ID}"
AXWAY_SERVICE_ACCOUNT_CLIENT_SECRET="${CLIENT_SECRET}"
# Note: Use these credentials to obtain an access token for AXWAY_API_TOKEN
EOF
    else
        cat >> "$ENV_FILE" << EOF

# API Token for callbacks (obtain from service account or other auth method)
# AXWAY_API_TOKEN=your-api-token-here
EOF
    fi
    
    print_success "Environment configuration created: $ENV_FILE"
    print_info "Add these environment variables to your application"
}

# Cleanup function
cleanup_files() {
    read -p "Keep generated files (YAML config, environment file)? [Y/n]: " KEEP_FILES
    if [[ "$KEEP_FILES" =~ ^[Nn]$ ]]; then
        rm -f "$YAML_FILE" "$ENV_FILE" service-account.json
        print_info "Generated files cleaned up"
    else
        print_info "Files kept:"
        [ -f "$YAML_FILE" ] && echo "  - $YAML_FILE"
        [ -f "$ENV_FILE" ] && echo "  - $ENV_FILE"
        [ -f "service-account.json" ] && echo "  - service-account.json"
    fi
}

# Display summary
show_summary() {
    print_header "Setup Summary"
    
    echo "✅ Integration created: $INTEGRATION_NAME"
    echo "✅ Webhook configured: $WEBHOOK_URL"
    echo "✅ Authentication secret set"
    echo "✅ Resource hooks configured for:"
    echo "   - API lifecycle events (created, updated, deleted)"
    echo "   - Subscription events (created, updated, deleted)"
    
    if [ "$SA_CREATED" = true ]; then
        echo "✅ Service account created for API callbacks"
    fi
    
    echo ""
    print_info "Next Steps:"
    echo "1. Source the environment file: source $ENV_FILE"
    echo "2. Update your webhook service configuration"
    echo "3. Test the webhook integration"
    echo "4. Monitor webhook events in Axway Central"
    
    echo ""
    print_info "Useful Commands:"
    echo "# View integration"
    echo "axway central get integ $INTEGRATION_NAME"
    echo ""
    echo "# View webhook"
    echo "axway central get webhook ${INTEGRATION_NAME}-webhook -s $INTEGRATION_NAME"
    echo ""
    echo "# View resource hooks"
    echo "axway central get resourcehook -s $INTEGRATION_NAME"
}

# Main execution
main() {
    print_header "Axway Amplify Central Webhook Setup"
    echo "This script will create the necessary Axway resources for webhook integration"
    echo ""
    
    check_prerequisites
    get_configuration
    create_yaml_config
    
    if deploy_configuration; then
        if verify_deployment; then
            create_service_account
            generate_env_config
            show_summary
            cleanup_files
            
            print_success "Axway webhook setup completed successfully!"
        else
            print_error "Deployment verification failed"
            exit 1
        fi
    else
        print_error "Deployment failed"
        exit 1
    fi
}

# Handle script arguments
case "$1" in
    "help"|"-h"|"--help")
        echo "Axway Amplify Central Webhook Setup Script"
        echo ""
        echo "Usage: $0 [options]"
        echo ""
        echo "Options:"
        echo "  help, -h, --help     Show this help message"
        echo "  cleanup              Remove existing integration (interactive)"
        echo ""
        echo "This script will:"
        echo "1. Check prerequisites (Axway CLI and authentication)"
        echo "2. Collect configuration (integration name, webhook URL, API key)"
        echo "3. Create YAML configuration with Integration, Secret, Webhook, and ResourceHook"
        echo "4. Deploy resources to Axway Central"
        echo "5. Verify deployment"
        echo "6. Optionally create service account for API callbacks"
        echo "7. Generate environment configuration file"
        echo ""
        echo "Prerequisites:"
        echo "- Axway CLI installed: npm install -g @axway/axway-central-cli"
        echo "- Authenticated: axway auth login"
        ;;
    "cleanup")
        print_header "Cleanup Existing Integration"
        read -p "Enter integration name to remove: " INTEGRATION_NAME
        if [ -n "$INTEGRATION_NAME" ]; then
            print_warning "This will remove the integration and all related resources"
            read -p "Are you sure? [y/N]: " CONFIRM
            if [[ "$CONFIRM" =~ ^[Yy]$ ]]; then
                axway central delete integ "$INTEGRATION_NAME"
                print_success "Integration removed"
            else
                print_info "Cleanup cancelled"
            fi
        fi
        ;;
    "")
        main
        ;;
    *)
        print_error "Unknown option: $1"
        echo "Use '$0 help' for usage information"
        exit 1
        ;;
esac